// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title ZKVerifier - Groth16 zk-SNARK proof verifier
contract ZKVerifier {
    // This interface is auto-generated by snarkjs or circomlib tools
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory publicSignals
    ) public view returns (bool) {}

    function validate(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory publicInputs
    ) external view returns (bool success) {
        return verifyProof(a, b, c, publicInputs);
    }
}
